README.md
To show the build status of our Travis CI
=> Added new badge

db/seeds.rb
Ensure we have a default admin user account to login when we deploy the code.
=> Added seed data for default admin user [#149979630]

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
=> Updated to Bootstrap 4 beta

spec/features/access_control_to_admin_pages_spec.rb, spec/features/manage_student_classes_spec.rb, spec/features/manage_student_phases_spec.rb, spec/features/manage_user_accounts_spec.rb, spec/features/manage_user_roles_spec.rb
=> Chore admin tests

Gemfile, Gemfile.lock, README.md, app/controllers/admin/users_controller.rb, app/mailers/application_mailer.rb, app/mailers/notifications_mailer.rb, app/views/devise/sessions/new.html.erb, app/views/layouts/mailer.html.erb, app/views/notifications_mailer/new_user.html.erb, app/views/notifications_mailer/new_user.text.erb, config/environments/development.rb, config/environments/production.rb, spec/features/manage_user_accounts_spec.rb, spec/mailers/notifications_spec.rb, spec/rails_helper.rb
- Included way to test the code in feature test.
=> Add email delivery for new user creation

app/controllers/admin/roles_controller.rb, app/controllers/application_controller.rb, app/views/pages/index.html.erb
[https://www.pivotaltracker.com/story/show/150578532]
=> Admin can navigate to admin pages

Gemfile.lock, README.md, spec/features/manage_school_classes_spec.rb, spec/rails_helper.rb
- Also fix accidentally focused test.
- Fix broken test.
=> Fix for Chromedriver on windows

app/controllers/application_controller.rb, app/helpers/devise_helper.rb, app/views/devise/registrations/edit.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/update_user_profiles_spec.rb
=> User can update own profile & password

app/models/internship_company.rb, app/models/internship_record.rb, app/models/internship_supervisor.rb, app/models/past_education_record.rb, app/models/remark.rb, app/models/student.rb, app/models/student_status_history.rb, spec/models/internship_company_spec.rb, spec/models/internship_record_spec.rb, spec/models/internship_supervisor_spec.rb, spec/models/past_education_record_spec.rb, spec/models/remark_spec.rb, spec/models/student_spec.rb, spec/models/student_status_history_spec.rb
=> Add validations

app/controllers/students_controller.rb, app/models/student.rb, app/views/students/edit.html.erb, app/views/students/index.html.erb, app/views/students/new.html.erb, app/views/students/shared/_student_form.html.erb, config/routes.rb, spec/features/manage_student_admissions_spec.rb
Added some student particulars since there were some not null constraints [#149345213]
[#149345211]
=> New student admissions

app/controllers/students_controller.rb, app/views/students/index.html.erb, app/views/students/show.html.erb, spec/features/manage_student_admissions_spec.rb
=> View student particulars

app/controllers/internship_companies_controller.rb, app/models/internship_company.rb, app/views/internship_companies/edit.html.erb, app/views/internship_companies/index.html.erb, app/views/internship_companies/new.html.erb, app/views/internship_companies/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_internship_company_form.html.erb, config/routes.rb, spec/features/manage_internship_companies_spec.rb, spec/rails_helper.rb
To manage list of internship companies by creating tables consisting of the following:
*Fields*
Name, Address, Postal Code
*Technical Notes*
The show view: Show list of internship supervisors
The show view: Show list of students assigned to company
Student Name
Supervisor assigned to student
from_date (link to internship_records table)
to_date (link to internship_records table)
URL: /internship_companies
Controller File: internship_companies_controller.rb
Views: index, new, create, show, edit, update, destroy
=> Manage internship companies [#150762793]

app/controllers/disabilities_controller.rb, app/views/disabilities/edit.html.erb, app/views/disabilities/index.html.erb, app/views/disabilities/new.html.erb, app/views/disabilities/shared/_disability_form.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/manage_disabilities_spec.rb
Manage master list of disabilities.
=> Feature disabilities

app/controllers/admin/school_classes_controller.rb, app/models/student.rb, app/views/admin/school_classes/index.html.erb, app/views/admin/school_classes/show.html.erb, app/views/admin/shared/_school_class_form.html.erb, app/views/internship_companies/show.html.erb, spec/features/assign_students_to_classes_spec.rb, spec/features/manage_school_classes_spec.rb, spec/models/student_spec.rb
As a Principal/Vice-Principal, i should be able to assign student to classes [#149345221]
=> Assign students to classes

app/controllers/past_education_records_controller.rb, app/controllers/point_of_contacts_controller.rb, app/controllers/students_controller.rb, app/models/point_of_contact.rb, app/models/student.rb, app/views/past_education_records/edit.html.erb, app/views/past_education_records/new.html.erb, app/views/past_education_records/shared/_past_education_record_form.html.erb, app/views/point_of_contacts/edit.html.erb, app/views/point_of_contacts/new.html.erb, app/views/point_of_contacts/shared/_point_of_contact_form.html.erb, app/views/students/edit.html.erb, app/views/students/index.html.erb, app/views/students/new.html.erb, app/views/students/shared/_student_form.html.erb, app/views/students/show.html.erb, config/routes.rb, spec/features/manage_past_education_records_spec.rb, spec/features/manage_point_of_contacts_spec.rb, spec/features/manage_student_admissions_spec.rb
=> Manage point of contacts

app/views/layouts/application.html.erb, app/views/students/index.html.erb, app/views/students/show.html.erb, spec/features/add_remark_spec.rb, spec/features/manage_student_admissions_spec.rb
Polish student view page and student search form
Move Students to main nav
Mark Remarks spec as pending
=> Polish student view page and student search form [#151575351]

app/controllers/internship_records_controller.rb, app/controllers/remarks_controller.rb, app/controllers/students_controller.rb, app/models/remark.rb, app/models/student.rb, app/views/students/shared/_admission_details.html.erb, app/views/students/shared/_internship_record_fields.html.erb, app/views/students/shared/_medical_history.html.erb, app/views/students/shared/_point_of_contact_fields.html.erb, app/views/students/shared/_remark_form.html.erb, app/views/students/shared/_student_form.html.erb, app/views/students/shared/_student_particulars.html.erb, db/seeds.rb, spec/features/manage_student_admissions_spec.rb, spec/features/manage_student_internships_spec.rb, spec/features/update_user_profiles_spec.rb
Internships form styling - TBC
The "Update Student" button doesn't show under any tab but "Internships" on my machine, but it shows on others.
=> Polish student form

app/controllers/students_controller.rb, app/models/student.rb, app/views/students/shared/_student_particulars.html.erb, app/views/students/show.html.erb, db/migrate/20171007072917_add_tshirt_size_to_students.rb, db/schema.rb, spec/features/manage_student_admissions_spec.rb
Manage student's t-shirt size: xs, s, m, l, xl, xxl, other
=> Manage student's t-shirt size

app/controllers/students_controller.rb, app/models/remark.rb, app/views/students/shared/_admission_details.html.erb, app/views/students/shared/_internship_record_fields.html.erb, app/views/students/shared/_medical_history.html.erb, app/views/students/shared/_point_of_contact_fields.html.erb, app/views/students/shared/_remark_form.html.erb, app/views/students/shared/_student_form.html.erb, app/views/students/shared/_student_particulars.html.erb, db/migrate/20171007142014_change_remark_category_to_string.rb, db/schema.rb, spec/features/manage_student_admissions_spec.rb
- Fix remarks nested fields
- Persist user who made the remark
- Fix formatting for responsive design in student form
=> Bug fix remarks

Gemfile, Gemfile.lock, app/controllers/students_controller.rb, app/views/students/index.html.erb, app/views/students/shared/_admission_details.html.erb, app/views/students/shared/_financial_assistance_record_form.html.erb, app/views/students/shared/_internship_record_fields.html.erb, app/views/students/shared/_past_education_record_fields.html.erb, app/views/students/shared/_point_of_contact_fields.html.erb, app/views/students/shared/_remark_form.html.erb, app/views/students/shared/_student_form.html.erb, app/views/students/shared/_student_particulars.html.erb, spec/factories/internship_companies.rb, spec/factories/internship_records.rb, spec/factories/internship_supervisors.rb, spec/factories/past_education_records.rb, spec/factories/roles.rb, spec/factories/students.rb, spec/factories/users.rb, spec/features/manage_past_education_records_spec.rb, spec/features/manage_point_of_contacts_spec.rb, spec/features/manage_student_admissions_spec.rb, spec/features/manage_student_internships_spec.rb, spec/rails_helper.rb, spec/support/factory_girl.rb
Used the standard dialog box for prompt - please feel free to suggest other options
=> Nested fields delete prompt

app/views/admin/shared/_school_class_form.html.erb, app/views/students/index.html.erb, app/views/students/show.html.erb, spec/features/manage_student_admissions_spec.rb
=> Bug show current class

app/models/point_of_contact.rb, app/views/students/shared/_point_of_contact_fields.html.erb, app/views/students/show.html.erb, db/migrate/20171014081600_add_mandatory_relationship_to_pointofcontacts.rb, db/schema.rb
- "Relationship" is a mandatory field
- Moved "Relationship" and phone numbers fields up for visibility
- Error message: "Point of contacts relationship : Parent/Guardian relationship is required"
=> Make point of contact relationship mandatory

app/views/admin/school_classes/show.html.erb, app/views/pages/index.html.erb, app/views/shared/_teacher_dashboard.html.erb, spec/factories/school_classes.rb, spec/features/assign_students_to_classes_spec.rb, spec/features/manage_school_classes_spec.rb, spec/features/manage_teacher_dashboard_spec.rb
=> Teacher dashboard

app/controllers/pages_controller.rb, app/views/students/shared/_student_form.html.erb, db/seeds.rb
Redirect principal dashboard to students index
Add cancel button on Add/Edit Student page
Fix Remarks user_id/user_name problem
Fix seeds
=> Chore fix bugs

app/controllers/students_controller.rb, db/seeds.rb
Fixed the disabilities and medical conditions duplication issue
Order Students by surname
Change super admin and teacher emails to real names
=> Fixed disabilities and medical seeding duplication [chore]

app/controllers/students_controller.rb, app/views/students/shared/_remark_form.html.erb, app/views/students/shared/_student_form.html.erb, spec/features/add_remark_spec.rb, spec/rails_helper.rb
Current implementation:
- Remarks are not editable but deletable by creator once created.
Run `chromedriver-update 2.36` if browser fail to start
=> Fix remark form

app/views/students/shared/_remark_form.html.erb
Fix datepicker format in remark form [#156063764]
=> Fix datepicker format in remark form

app/views/students/shared/_admission_details.html.erb, app/views/students/shared/_student_form.html.erb, spec/features/manage_student_admissions_spec.rb
=> Invert key and value for Student Status and Referred by [#156063744]

app/views/students/index.html.erb
=> Fix Boostrap 4 formatting for search [#156414765]

app/views/admin/roles/index.html.erb, app/views/admin/roles/shared/_role_row.html.erb, app/views/admin/school_classes/index.html.erb, app/views/admin/school_classes/shared/_school_class_row.html.erb, app/views/admin/users/index.html.erb, app/views/admin/users/shared/_user_row.html.erb, app/views/disabilities/index.html.erb, app/views/disabilities/shared/_disability_row.html.erb, app/views/internship_companies/index.html.erb, app/views/internship_companies/shared/_internship_company_row.html.erb, app/views/internship_supervisors/index.html.erb, app/views/internship_supervisors/shared/_internship_supervisor_row.html.erb, app/views/medical_conditions/index.html.erb, app/views/medical_conditions/shared/_medical_condition_row.html.erb
Use render partial with collection instead of looping through each item in collections.
=> Reduce memory usage when rendering the views. [chore]

db/seeds.rb
For seeding the production instance with the right amount of data.
=> Only run certain things for production seed

app/controllers/students_controller.rb, spec/features/manage_photo_upload_spec.rb, spec/features/manage_student_admissions_spec.rb
The empty "attachment" record is making things confusing. Will empty out the sections so need explicit "Add new XXX" button to be clicked to add new sub records.
=> Fix missing upload button

config/environments/production.rb
=> Add default mailer host

app/controllers/students_controller.rb, app/views/students/shared/_admission_details.html.erb, app/views/students/shared/_student_particulars.html.erb, app/views/students/show.html.erb, config/initializers/devise.rb, db/migrate/20181215031743_add_contact_number_to_students.rb, db/schema.rb
- Add contact details (home and mobile number).
- Add home address & postal code.
=> Feature update fields
